server:
  port: 8082

spring:
  application:
    name: kinoved-file-manager

  kafka:
    bootstrap-servers: "127.0.0.1:9092"
    consumer:
      client-id: "consumer-kinoved-file-manager"
      group-id: "group-kinoved-file-manager"
      auto-offset-reset: earliest
    producer:
      client-id: "producer-kinoved-file-manager"

app:
  settings:
    source-directory: D:/_Kinoved/movies source
    target-directory: D:/_Kinoved/movies genres
    source-directory-scan-interval: 5000
    undefined-genre-folder: "undefined"

  kafka:
    topics:
      file-task:
        name: "file-task-topic"
        partitions: 1
        replicas: 1
      file-notify:
        name: "file-notify-topic"
        partitions: 1
        replicas: 1
    consumer:
      max-poll-records: 1
      max-poll-interval: 10000
    listener:
      poll-timeout: 1000



